@echo off
REM ###########################################################################
REM Script generated by Fortify SCA Scan Wizard (c) 2011-2019 Micro Focus or one of its affiliates
REM Created on 2019/09/12 18:32:59
REM ###########################################################################
REM Generated for the following languages:
REM 	C#.NET / VB.NET
REM 	HTML
REM 	JavaScript / TypeScript
REM 	XML
REM ###########################################################################
REM DEBUG - if set to true, runs SCA in debug mode
REM SOURCEANALYZER - the name of the SCA executable
REM FPR - the name of analysis result file
REM BUILDID - the SCA build id
REM ARGFILE - the name of the argument file that's extracted and passed to SCA
REM BYTECODE_ARGFILE - the name of the argument file for Java Bytecode translation that's extracted and passed to SCA
REM MEMORY - the memory settings for SCA
REM SCANSWITCHES - parameters to be passed to the analysis phase of SCA
REM LAUNCHERSWITCHES - the launcher settings that are used to invoke SCA
REM OLDFILENUMBER - this defines the file which contains the number of files within the project, it is automatically generated
REM FILENOMAXDIFF - this is the percentage of difference between the number of files which will trigger a warning by the script
REM ###########################################################################

set DEBUG=false
set SOURCEANALYZER=sourceanalyzer
set FPR="Fortify_Kana-Prechat-Migration.fpr"
set BUILDID="%4"
set ARGFILE="Fortify_Kana-Prechat-Migration.bat.args"
set BYTECODE_ARGFILE="Fortify_Kana-Prechat-Migration.bat.bytecode.args"
set MEMORY=-Xmx16G -Xms16G -Xss16G
set LAUNCHERSWITCHES=""
set SCANSWITCHES=""
set OLDFILENUMBER=Fortify_Kana-Prechat-Migration.bat.fileno
set FILENOMAXDIFF=10
set ENABLE_BYTECODE=false
set FULLSCAN="FULLSCAN"
set MODIFIEDSCAN="MODIFIEDSCAN"
set PROJECTROOT0=%1
set SCANMODE=%2
set MODIFIEDFILECHANGES=%3
REM ###########################################################################
ECHO PROJECTROOT : %PROJECTROOT0%
ECHO SOURCEANALYZER: %SOURCEANALYZER%
ECHO FPR: %FPR%
ECHO BUILDID: %BUILDID%
ECHO ARGFILE: %ARGFILE%
ECHO BYTECODE_ARGFILE: %BYTECODE_ARGFILE%
ECHO MEMORY: %MEMORY%
ECHO LAUNCHERSWITCHES: %LAUNCHERSWITCHES%
ECHO SCANSWITCHES: %SCANSWITCHES%
ECHO OLDFILENUMBER: %OLDFILENUMBER%
ECHO FILENOMAXDIFF: %FILENOMAXDIFF%
ECHO ENABLE_BYTECODE: %ENABLE_BYTECODE%
ECHO SCANMODE: %SCANMODE%
ECHO MODIFIEDFILECHANGES: %MODIFIEDFILECHANGES%
REM ###########################################################################

IF NOT EXIST %PROJECTROOT0% (
   ECHO  ERROR: This script is being run on a different machine than it was
   ECHO         generated on or the targeted project has been moved. This script is 
   ECHO         configured to locate files at
   ECHO            %PROJECTROOT0%
   ECHO         Please modify the %%PROJECTROOT0%% variable found
   ECHO         at the top of this script to point to the corresponding directory
   ECHO         located on this machine.
   GOTO :FINISHED
)

IF %DEBUG%==true set LAUNCHERSWITCHES=-debug %LAUNCHERSWITCHES%
echo Extracting Arguments File


echo. >%ARGFILE%
echo. >%BYTECODE_ARGFILE%
SETLOCAL ENABLEDELAYEDEXPANSION
IF EXIST %0 (
   set SCAScriptFile=%0
) ELSE (
  set SCAScriptFile=%0.bat
)

set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM ARGS" %SCAScriptFile%' ) DO (
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!  
   echo !argVal:~9! >> %ARGFILE%   
)

REM ####################  FULL SCAN  #######################################################
IF %SCANMODE%==%FULLSCAN% (
echo %PROJECTROOT0% >> %ARGFILE%
)

REM ####################  MODIFIED SCAN  #######################################################
IF %SCANMODE%==%MODIFIEDSCAN% (
	IF EXIST %MODIFIEDFILECHANGES% (
		FOR /F "tokens=* delims=" %%i IN  (%MODIFIEDFILECHANGES%) DO (         
			echo "%%i" >> %ARGFILE%
		)
	)
)
set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM BYTECODE_ARGS" %SCAScriptFile%' ) DO (
   set ENABLE_BYTECODE=true
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!
   echo !argVal:~18! >> %BYTECODE_ARGFILE%
)
ENDLOCAL && set ENABLE_BYTECODE=%ENABLE_BYTECODE%

REM ###########################################################################

echo Searching .NET Framework Version...
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2" (
set LAUNCHERSWITCHES=-dotnet-version 4.6.2 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.6.2
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1" (
set LAUNCHERSWITCHES=-dotnet-version 4.6.1 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.6.1
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6" (
set LAUNCHERSWITCHES=-dotnet-version 4.6 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.6
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2" (
set LAUNCHERSWITCHES=-dotnet-version 4.5.2 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.5.2
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1" (
set LAUNCHERSWITCHES=-dotnet-version 4.5.1 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.5.1
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5" (
set LAUNCHERSWITCHES=-dotnet-version 4.5 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.5
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0" (
set LAUNCHERSWITCHES=-dotnet-version 4.0 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.0
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5" (
set LAUNCHERSWITCHES=-dotnet-version 3.5 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 3.5
GOTO DOTNETSELECTED
)
reg QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0" /v Install 2>NUL >NUL
IF %ERRORLEVEL%==0 (
set LAUNCHERSWITCHES=-dotnet-version 3.0 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 3.0
GOTO DOTNETSELECTED
)
reg QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727" /v Install 2>NUL >NUL
IF %ERRORLEVEL%==0 (
set LAUNCHERSWITCHES=-dotnet-version 2.0 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 2.0
GOTO DOTNETSELECTED
)
:DOTNETSELECTED
REM ###########################################################################

set SCANSWITCHES=-Dcom.fortify.sca.Phase0HigherOrder.Languages=javascript,typescript %SCANSWITCHES%

REM ###########################################################################
echo Cleaning previous scan artifacts
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% -clean 
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Translating files
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% @%ARGFILE%
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
IF %ENABLE_BYTECODE%==true (
echo Translating Java bytecode files
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% @%BYTECODE_ARGFILE%
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
)
REM ###########################################################################
REM echo Testing Difference between Translations
REM SETLOCAL
REM FOR /F "delims=" %%A in ('%SOURCEANALYZER% -b %BUILDID% -show-files ^| findstr /R /N "^" ^| find /C ":" ') DO SET FILENUMBER=%%A
REM IF NOT EXIST %OLDFILENUMBER% (
REM 	ECHO It appears to be the first time running this script, setting %OLDFILENUMBER% to %FILENUMBER%
REM 	ECHO %FILENUMBER% > %OLDFILENUMBER%
REM 	GOTO TESTENDED
REM )

REM FOR /F "delims=" %%i IN (%OLDFILENUMBER%) DO SET OLDFILENO=%%i
REM set /a DIFF=%OLDFILENO% * %FILENOMAXDIFF%
REM set /a DIFF /=  100
REM set /a MAX=%OLDFILENO% + %DIFF%
REM set /a MIN=%OLDFILENO% - %DIFF%

REM IF %FILENUMBER% LSS %MIN% set SHOWWARNING=true
REM IF %FILENUMBER% GTR %MAX% set SHOWWARNING=true

REM IF DEFINED SHOWWARNING (
REM ECHO WARNING: The number of files has changed by over %FILENOMAXDIFF%%%, it is recommended 
REM 	ECHO          that this script is regenerated with the ScanWizard
REM )
REM :TESTENDED
REM ENDLOCAL

REM ###########################################################################
echo Starting scan
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% %SCANSWITCHES% -scan -f %FPR%
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Finished
:FINISHED
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\Microsoft.CSharp.4.5.0\lib\netcore50\Microsoft.CSharp.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\Microsoft.CSharp.4.5.0\lib\netstandard1.3\Microsoft.CSharp.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\Microsoft.CSharp.4.5.0\lib\netstandard2.0\Microsoft.CSharp.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\Microsoft.CSharp.4.5.0\ref\netcore50\Microsoft.CSharp.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\Microsoft.CSharp.4.5.0\ref\netstandard1.0\Microsoft.CSharp.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\Microsoft.CSharp.4.5.0\ref\netstandard2.0\Microsoft.CSharp.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\Newtonsoft.Json.12.0.2\lib\net20\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\Newtonsoft.Json.12.0.2\lib\net35\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\Newtonsoft.Json.12.0.2\lib\net40\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\Newtonsoft.Json.12.0.2\lib\net45\Newtonsoft.Json.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\Newtonsoft.Json.12.0.2\lib\netstandard1.0\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\Newtonsoft.Json.12.0.2\lib\netstandard1.3\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\Newtonsoft.Json.12.0.2\lib\netstandard2.0\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\Newtonsoft.Json.12.0.2\lib\portable-net40+sl5+win8+wp8+wpa81\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\Newtonsoft.Json.12.0.2\lib\portable-net45+win8+wp8+wpa81\Newtonsoft.Json.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\System.Net.Http.4.3.4\lib\net46\System.Net.Http.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\System.Net.Http.4.3.4\ref\net46\System.Net.Http.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\System.Net.Http.4.3.4\ref\netcore50\System.Net.Http.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\System.Net.Http.4.3.4\ref\netstandard1.1\System.Net.Http.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\System.Net.Http.4.3.4\ref\netstandard1.3\System.Net.Http.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\System.Net.Http.4.3.4\runtimes\unix\lib\netstandard1.6\System.Net.Http.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\System.Net.Http.4.3.4\runtimes\win\lib\net46\System.Net.Http.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\System.Net.Http.4.3.4\runtimes\win\lib\netcore50\System.Net.Http.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\System.Net.Http.4.3.4\runtimes\win\lib\netstandard1.3\System.Net.Http.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\System.Threading.Tasks.4.3.0\ref\netcore50\System.Threading.Tasks.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\System.Threading.Tasks.4.3.0\ref\netstandard1.0\System.Threading.Tasks.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\packages\System.Threading.Tasks.4.3.0\ref\netstandard1.3\System.Threading.Tasks.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Debug\Interop.SHDocVw.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Debug\TempPE\Classes.PhysicalHealth.designer.cs.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Debug\TempPE\Service References.GSService.Reference.cs.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Debug\TempPE\Service References.LAWWService.Reference.cs.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Debug\TempPE\Service References.LawwServiceRefernce.Reference.cs.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Debug\TempPE\Service References.myUHCService.Reference.cs.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Debug\TempPE\Service References.OptumIDSupportChatServiceReference.Reference.cs.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Debug\TempPE\Service References.PhysicalHealthChatServiceReference.Reference.cs.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Release\Interop.SHDocVw.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Release\Package\PackageTmp\bin\AjaxControlToolkit.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Release\Package\PackageTmp\bin\Interop.SHDocVw.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Release\Package\PackageTmp\bin\opentoken-agent.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Release\Package\PackageTmp\bin\UIAutomationClient.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Release\Package\PackageTmp\bin\UIAutomationTypes.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Release\TempPE\Classes.PhysicalHealth.designer.cs.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Release\TempPE\Service References.OptumIDSupportChatServiceReference.Reference.cs.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Release\TempPE\Service References.PhysicalHealthChatServiceReference.Reference.cs.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\obj\Release\TempPE\Service References.ServiceReference1.Reference.cs.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChatHistory\obj\Debug\TempPE\Classes.PhysicalHealthChat.designer.cs.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChatHistory\obj\Release\TempPE\Classes.PhysicalHealthChat.designer.cs.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChatService\obj\Debug\TempPE\UHG_myUHC.designer.cs.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChatService\obj\Debug\TempPE\UHG_OptumIDSupport.designer.cs.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChatService\obj\Release\TempPE\UHG_OptumIDSupport.designer.cs.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChatService\obj\Release\TempPE\UHG_PhysicalHealth.designer.cs.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\obj\Debug\TempPE\Classes.OptumClinicalLicensureChat.designer.cs.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\obj\Debug\TempPE\Classes.SMERTChat.designer.cs.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\obj\Release\Package\PackageTmp\bin\AjaxControlToolkit.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\obj\Release\Package\PackageTmp\bin\Newtonsoft.Json.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\OptumClinicalLicensureChat\obj\Release\Package\PackageTmp\bin\OptumClinicalLicensureChat.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\obj\Release\TempPE\Classes.OptumClinicalLicensureChat.designer.cs.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\Microsoft.CSharp.4.5.0\lib\netcore50\Microsoft.CSharp.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\Microsoft.CSharp.4.5.0\lib\netstandard1.3\Microsoft.CSharp.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\Microsoft.CSharp.4.5.0\lib\netstandard2.0\Microsoft.CSharp.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\Microsoft.CSharp.4.5.0\ref\netcore50\Microsoft.CSharp.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\Microsoft.CSharp.4.5.0\ref\netstandard1.0\Microsoft.CSharp.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\Microsoft.CSharp.4.5.0\ref\netstandard2.0\Microsoft.CSharp.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\Newtonsoft.Json.12.0.2\lib\net20\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\Newtonsoft.Json.12.0.2\lib\net35\Newtonsoft.Json.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\Newtonsoft.Json.12.0.2\lib\net40\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\Newtonsoft.Json.12.0.2\lib\net45\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\Newtonsoft.Json.12.0.2\lib\netstandard1.0\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\Newtonsoft.Json.12.0.2\lib\netstandard1.3\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\Newtonsoft.Json.12.0.2\lib\netstandard2.0\Newtonsoft.Json.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\Newtonsoft.Json.12.0.2\lib\portable-net40+sl5+win8+wp8+wpa81\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\Newtonsoft.Json.12.0.2\lib\portable-net45+win8+wp8+wpa81\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\System.Net.Http.4.3.4\lib\net46\System.Net.Http.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\System.Net.Http.4.3.4\ref\net46\System.Net.Http.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\System.Net.Http.4.3.4\ref\netcore50\System.Net.Http.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\System.Net.Http.4.3.4\ref\netstandard1.1\System.Net.Http.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\System.Net.Http.4.3.4\ref\netstandard1.3\System.Net.Http.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\System.Net.Http.4.3.4\runtimes\unix\lib\netstandard1.6\System.Net.Http.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\System.Net.Http.4.3.4\runtimes\win\lib\net46\System.Net.Http.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\System.Net.Http.4.3.4\runtimes\win\lib\netcore50\System.Net.Http.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\System.Net.Http.4.3.4\runtimes\win\lib\netstandard1.3\System.Net.Http.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\System.Threading.Tasks.4.3.0\ref\netcore50\System.Threading.Tasks.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\System.Threading.Tasks.4.3.0\ref\netstandard1.0\System.Threading.Tasks.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\packages\System.Threading.Tasks.4.3.0\ref\netstandard1.3\System.Threading.Tasks.dll;PROJECTROOT0_MARKER\physicalhealth\packages\Microsoft.CSharp.4.5.0\lib\netcore50\Microsoft.CSharp.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\physicalhealth\packages\Microsoft.CSharp.4.5.0\lib\netstandard1.3\Microsoft.CSharp.dll;PROJECTROOT0_MARKER\physicalhealth\packages\Microsoft.CSharp.4.5.0\lib\netstandard2.0\Microsoft.CSharp.dll;PROJECTROOT0_MARKER\physicalhealth\packages\Microsoft.CSharp.4.5.0\ref\netcore50\Microsoft.CSharp.dll;PROJECTROOT0_MARKER\physicalhealth\packages\Microsoft.CSharp.4.5.0\ref\netstandard1.0\Microsoft.CSharp.dll;PROJECTROOT0_MARKER\physicalhealth\packages\Microsoft.CSharp.4.5.0\ref\netstandard2.0\Microsoft.CSharp.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\physicalhealth\packages\Newtonsoft.Json.12.0.2\lib\net20\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\physicalhealth\packages\Newtonsoft.Json.12.0.2\lib\net35\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\physicalhealth\packages\Newtonsoft.Json.12.0.2\lib\net40\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\physicalhealth\packages\Newtonsoft.Json.12.0.2\lib\net45\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\physicalhealth\packages\Newtonsoft.Json.12.0.2\lib\netstandard1.0\Newtonsoft.Json.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\physicalhealth\packages\Newtonsoft.Json.12.0.2\lib\netstandard1.3\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\physicalhealth\packages\Newtonsoft.Json.12.0.2\lib\netstandard2.0\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\physicalhealth\packages\Newtonsoft.Json.12.0.2\lib\portable-net40+sl5+win8+wp8+wpa81\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\physicalhealth\packages\Newtonsoft.Json.12.0.2\lib\portable-net45+win8+wp8+wpa81\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\physicalhealth\packages\System.Net.Http.4.3.4\lib\net46\System.Net.Http.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\physicalhealth\packages\System.Net.Http.4.3.4\ref\net46\System.Net.Http.dll;PROJECTROOT0_MARKER\physicalhealth\packages\System.Net.Http.4.3.4\ref\netcore50\System.Net.Http.dll;PROJECTROOT0_MARKER\physicalhealth\packages\System.Net.Http.4.3.4\ref\netstandard1.1\System.Net.Http.dll;PROJECTROOT0_MARKER\physicalhealth\packages\System.Net.Http.4.3.4\ref\netstandard1.3\System.Net.Http.dll;PROJECTROOT0_MARKER\physicalhealth\packages\System.Net.Http.4.3.4\runtimes\unix\lib\netstandard1.6\System.Net.Http.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\physicalhealth\packages\System.Net.Http.4.3.4\runtimes\win\lib\net46\System.Net.Http.dll;PROJECTROOT0_MARKER\physicalhealth\packages\System.Net.Http.4.3.4\runtimes\win\lib\netcore50\System.Net.Http.dll;PROJECTROOT0_MARKER\physicalhealth\packages\System.Net.Http.4.3.4\runtimes\win\lib\netstandard1.3\System.Net.Http.dll;PROJECTROOT0_MARKER\physicalhealth\packages\System.Threading.Tasks.4.3.0\ref\netcore50\System.Threading.Tasks.dll;PROJECTROOT0_MARKER\physicalhealth\packages\System.Threading.Tasks.4.3.0\ref\netstandard1.0\System.Threading.Tasks.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\physicalhealth\packages\System.Threading.Tasks.4.3.0\ref\netstandard1.3\System.Threading.Tasks.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChat\obj\Debug\TempPE\Classes.PhysicalHealth.designer.cs.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChat\obj\Debug\TempPE\Service References.GSService.Reference.cs.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChat\obj\Debug\TempPE\Service References.LAWWService.Reference.cs.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChat\obj\Debug\TempPE\Service References.LawwServiceRefernce.Reference.cs.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChat\obj\Debug\TempPE\Service References.myUHCService.Reference.cs.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChat\obj\Debug\TempPE\Service References.PhysicalHealthChatServiceReference.Reference.cs.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChat\obj\Release\TempPE\Classes.PhysicalHealth.designer.cs.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChat\obj\Release\TempPE\Service References.PhysicalHealthChatServiceReference.Reference.cs.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChatHistory\obj\Debug\TempPE\Classes.PhysicalHealthChat.designer.cs.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChatHistory\obj\Release\TempPE\Classes.PhysicalHealthChat.designer.cs.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChatService\obj\Debug\TempPE\UHG_myUHC.designer.cs.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChatService\obj\Debug\TempPE\UHG_PhysicalHealth.designer.cs.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChatService\obj\Release\Package\PackageTmp\bin\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChatService\obj\Release\Package\PackageTmp\bin\PhysicalHealthChatService.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChatService\obj\Release\TempPE\UHG_PhysicalHealth.designer.cs.dll;PROJECTROOT0_MARKER\RealestatechatPreChat\packages\AjaxControlToolkit.18.1.1\lib\net40\AjaxControlToolkit.dll;PROJECTROOT0_MARKER\RealestatechatPreChat\RealEstateChatHistory\obj\Debug\TempPE\Classes.RealEstate.designer.cs.dll;PROJECTROOT0_MARKER\RealestatechatPreChat\RealEstateChatHistory\obj\Release\Package\PackageTmp\bin\AjaxControlToolkit.dll;PROJECTROOT0_MARKER\RealestatechatPreChat\RealEstateChatHistory\obj\Release\TempPE\Classes.RealEstate.designer.cs.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\RealestatechatPreChat\RealEstateChatService\obj\Debug\TempPE\UHG_RealEstate.designer.cs.dll;PROJECTROOT0_MARKER\RealestatechatPreChat\RealEstateChatService\obj\Release\TempPE\UHG_RealEstate.designer.cs.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\KanaChat_RXSolutions\bin\KanaChat_RXSolutions.dll.config;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\KanaChat_RXSolutions\bin\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\kanachat_rxsolutions\KanaChat_RXSolutions\KanaChat_RXSolutions\bin\Newtonsoft.Json.xml"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\bin\AjaxControlToolkit.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\bin\Interop.SHDocVw.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\bin\opentoken-agent.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\bin\OptumIDSupportChat.dll.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\bin\UIAutomationClient.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChat\bin\UIAutomationTypes.dll;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupport.sln;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\close.html;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Error.aspx;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Index.aspx"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\js\responseLiveChat.js;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Scripts\jquery-1.4.1-vsdoc.js;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Scripts\jquery-1.4.1.js;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Scripts\jquery-1.4.1.min.js;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Service References\OptumIDSupportChatServiceReference\OptumIDSupportService.xsd"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Service References\OptumIDSupportChatServiceReference\OptumIDSupportService1.xsd;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Service References\OptumIDSupportChatServiceReference\OptumIDSupportService2.xsd;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Survey.aspx;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Web.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Web.Debug.config"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Web.Release.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Webconfig\DEV\Web.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Webconfig\DEV\Web.Debug.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Webconfig\DEV\Web.Release.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Webconfig\PRD\Web.config"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Webconfig\PRD\Web.Debug.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Webconfig\PRD\Web.Release.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Webconfig\STG\Web.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Webconfig\STG\Web.Debug.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Webconfig\STG\Web.Release.config"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Webconfig\TST\Web.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Webconfig\TST\Web.Debug.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChat\Webconfig\TST\Web.Release.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChatHistory\Agent\PhysicalHealthChatRecords.aspx;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChatHistory\Agent\PhysicalHealthChatViewTranscript.aspx"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChatHistory\App_Data\DispositionCodes.xml;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChatHistory\App_Data\GridItemsPerPage.xml;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChatHistory\CommonPages\CommonError.aspx;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChatHistory\Default.aspx;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChatHistory\OptumIDSupportChatHistoryMasterPage.master"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChatHistory\Web.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChatHistory\Web.Debug.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChatHistory\Web.Release.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\Backup\OptumIDSupportChatService\Web.config;PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChatHistory\bin\OptumIDSupportChatHistory.dll.config"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Optum ID Support\trunk\OptumIDSupportChatService\bin\OptumIDSupportChatService.dll.config;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\Backup\Default.aspx;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\Backup\js\responseLiveChat.js;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\Backup\OptumClinicalLicensureChat.sln;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\Backup\Scripts\jquery-1.10.2.js"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\OptumClinicalLicensureChat\Backup\Scripts\jquery-1.4.1-vsdoc.js;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\Backup\Scripts\jquery-1.4.1.js;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\Backup\Scripts\jquery-1.4.1.min.js;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\Backup\Scripts\jquery-ui.js;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\Backup\Web.config"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\OptumClinicalLicensureChat\Backup\Web.Debug.config;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\Backup\Web.Release.config;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\bin\AjaxControlToolkit.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\bin\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\OptumClinicalLicensureChat\bin\Newtonsoft.Json.xml"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\OptumClinicalLicensureChat\bin\OptumClinicalLicensureChat.dll.config;PROJECTROOT0_MARKER\physicalhealth\Backup\PhysicalHealth.sln;PROJECTROOT0_MARKER\physicalhealth\Backup\PhysicalHealthChatHistory\Agent\PhysicalHealthChatRecords.aspx;PROJECTROOT0_MARKER\physicalhealth\Backup\PhysicalHealthChatHistory\Agent\PhysicalHealthChatViewTranscript.aspx;PROJECTROOT0_MARKER\physicalhealth\Backup\PhysicalHealthChatHistory\App_Data\DispositionCodes.xml"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\physicalhealth\Backup\PhysicalHealthChatHistory\App_Data\GridItemsPerPage.xml;PROJECTROOT0_MARKER\physicalhealth\Backup\PhysicalHealthChatHistory\CommonPages\CommonError.aspx;PROJECTROOT0_MARKER\physicalhealth\Backup\PhysicalHealthChatHistory\Default.aspx;PROJECTROOT0_MARKER\physicalhealth\Backup\PhysicalHealthChatHistory\PhysicalHealthChatHistoryMasterPage.master;PROJECTROOT0_MARKER\physicalhealth\Backup\PhysicalHealthChatHistory\Web.config"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\physicalhealth\Backup\PhysicalHealthChatHistory\Web.Debug.config;PROJECTROOT0_MARKER\physicalhealth\Backup\PhysicalHealthChatHistory\Web.Release.config;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChat\bin\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChat\bin\Newtonsoft.Json.xml;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChat\bin\opentoken-agent.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChat\bin\UIAutomationClient.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChat\bin\UIAutomationTypes.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChatHistory\bin\PhysicalHealthChatHistory.dll.config;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChatService\bin\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChatService\bin\Newtonsoft.Json.xml"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChatService\bin\PhysicalHealthChatService.dll.config;PROJECTROOT0_MARKER\RealestatechatPreChat\RealEstateChatHistory\bin\AjaxControlToolkit.dll;PROJECTROOT0_MARKER\RealestatechatPreChat\RealEstateChatHistory\bin\RealEstateChatHistory.dll.config;PROJECTROOT0_MARKER\RealestatechatPreChat\RealEstateChatService\bin\RealEstateChatService.dll.config"









REM ARGS "-exclude" "PROJECTROOT0_MARKER\UMRChat\UMRChat\Scripts\jquery-1.4.1-vsdoc.js"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\UMRChat\UMRChat\Scripts\jquery-1.4.1.js"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\UMRChat\UMRChat\Scripts\jquery-1.4.1.min.js"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\UMRChat\UMRChat\widgets"

REM ARGS "-exclude" "PROJECTROOT0_MARKER\RealEstateChat\RealEstateChat\Scripts\jquery-1.4.1-vsdoc.js"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\RealEstateChat\RealEstateChat\Scripts\jquery-1.10.2.js"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\RealEstateChat\RealEstateChat\Scripts\jquery-1.4.1.min.js"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\RealEstateChat\RealEstateChat\Scripts\jquery-ui.js"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\RealEstateChat\RealEstateChat\widgets"

REM ARGS "-exclude" "PROJECTROOT0_MARKER\SDChat\SDChat\Scripts\jquery-1.4.1-vsdoc.js"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\SDChat\SDChat\Scripts\jquery-1.4.1.js"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\SDChat\SDChat\Scripts\jquery-1.4.1.min.js"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\SDChat\SDChat\widgets"


REM ARGS "-exclude" "PROJECTROOT0_MARKER\PhysicalHealthChat\PhysicalHealthChat\Scripts\jquery-1.4.1-vsdoc.js"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\PhysicalHealthChat\PhysicalHealthChat\Scripts\jquery-1.4.1.js"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\PhysicalHealthChat\PhysicalHealthChat\Scripts\jquery-1.10.2.js"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\PhysicalHealthChat\PhysicalHealthChat\Scripts\jquery-1.4.1.min.js"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\PhysicalHealthChat\PhysicalHealthChat\widgets"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\PhysicalHealthChat\PhysicalHealthChatService\bin\Newtonsoft.Json.xml"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\physicalhealth\PhysicalHealthChatService\bin\PhysicalHealthChatService.dll.config"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\PhysicalHealthChat\PhysicalHealthChatService\bin\LAWWChatService.dll"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\PhysicalHealthChat\PhysicalHealthChatService\bin\OptumBankChatService.dll"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\PhysicalHealthChat\PhysicalHealthChatService\bin\PhysicalHealthChatService.dll"

REM ARGS "-exclude" "PROJECTROOT0_MARKER\ProHealthCare\ProHealthCare\Resources\Newtonsoft.Json.dll"

REM ARGS "-exclude" "PROJECTROOT0_MARKER\OptumIDSupportChat\OptumIDSupportChat\Scripts"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\OptumIDSupportChat\OptumIDSupportChat\widgets"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\OptumIDSupportChat\OptumIDSupportChatService\bin\OptumIDSupportChatService.dll.config"


REM ARGS "-exclude" "PROJECTROOT0_MARKER\KanaChat_RXSolutions\KanaChat_RXSolutions\Scripts"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\KanaChat_RXSolutions\KanaChat_RXSolutions\widgets"

REM ARGS "-exclude" "PROJECTROOT0_MARKER\OCLChat\OCLChat\Scripts"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\OCLChat\OCLChat\widgets"

REM ARGS "-exclude" "PROJECTROOT0_MARKER\OHBSSTARUM\OHBSSTARUM\Scripts"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\OHBSSTARUM\OHBSSTARUM\widgets"

REM ARGS "-exclude" "PROJECTROOT0_MARKER\RealEstateChat\RealEstateChat\Scripts"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\RealEstateChat\RealEstateChat\widgets"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\RealestatechatPreChat\RealEstateChatService\bin\RealEstateChatService.dll.config"

REM ARGS "-exclude" "PROJECTROOT0_MARKER\SalesOneChat\SalesOneChat\Scripts"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\SalesOneChat\SalesOneChat\widgets"

REM ARGS "-exclude" "PROJECTROOT0_MARKER\SDChat\SDChat\Scripts"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\SDChat\SDChat\widgets"


REM ARGS "-exclude" "PROJECTROOT0_MARKER\SMERTChat\SMERTChat\Scripts"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\SMERTChat\SMERTChat\widgets"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\jenkinsfile"
